### PR TITLE
first draft implementing upload report stats into the main CLI code

### PR DESCRIPTION
**Pull request by eacmen**
This is to replace @rflmk manual SQL queries to generate useful usage data based on Organizations.

### CODE REVIEW

**Comment by rflmk** [comment]
the data format looks good in general

**Comment by eacmen** [comment]
> comment to remind myself to look up frontend-api status:
> right now this will return inaccurate results since it doesn't include deleted reports. so it will only show what's currently on the dashboard, not overall upload statistics.
> on the other hand, maybe that's a valid data set. maybe that's what the customer wants after all.
> 
> another thing to note, this doesn't return info for users that don't have an organization. i think we should add those reports also, but note them somehow as not belonging to an organization. maybe just leave the "Organization" field empty?

Yes I considered the Null organization issue. Maybe grouping those users into an org with their username as the org name?

**Comment by eacmen** [comment]
> does the version get bumped automatically now or do we still have to manually set that somewhere?

It does not happen automatically needs to get bumped before being merged. If the version number is not bumped then the eventual release tag WILL fail CI.

**Comment by rflmk** [comment]
> Yes I considered the Null organization issue. Maybe grouping those users into an org with their username as the org name?

yes that's a good idea, for the summary we can use their username as the organization name if they are not associated with an org.   for the detail view i suppose we could do the same thing, put their username in the organization column. or leave that blank

**Comment by eacmen** [comment]
> > Yes I considered the Null organization issue. Maybe grouping those users into an org with their username as the org name?
> 
> yes that's a good idea, for the summary we can use their username as the organization name if they are not associated with an org. for the detail view i suppose we could do the same thing, put their username in the organization column. or leave that blank

This is now implemented as an optional flag `--include-individuals`.

**Pull request merged**
